### ISSUE TITLE
Limitations regarding Multithreading

### ISSUE THREAD

**Issue by Binero** [PistonDevelopers/glfw-rs#238]
The `Glfw` structure was implemented to enforce that some functions can only be called from the main thread. This structure seems to not been implemented right however: it is limiting function calls to perfectly thread-safe GLFW functions.  Examples of these are `make_context_current`, `get_time`, `set_time` and `set_swap_interval`. All of these functions are thread-safe, but for some reason rely on the `Glfw`-struct. 

A secondary issue is that the `Window` structure carries a copy of the `Glfw` structure. Even if we moved the thread-safe functions outside of the `Glfw` structure, we still wouldn't be able to call window-specific functions from other threads.

A good solution would be to copy the thread-safe functions outside of the `Glfw` structure, mark the `Glfw` ones as deprecated and make them call their moved equivalents. 

The `Window` structure cannot be fixed without breaking existing code however. People might have relied on there being a `Glfw` structure inside their windows, and thus taking it out will result in errors.

I am willing to do a pull-request for this, but I think this needs further discussion.

**Comment by bvssvni** [comment]
Related thread: https://github.com/PistonDevelopers/glfw-rs/issues/473
