### ISSUE TITLE
Add support for setting the cursor

### ISSUE THREAD

**Issue by nstoddard** [PistonDevelopers/glfw-rs#288]
It looks like this library doesn't support changing the cursor (via the glfwSetCursor function). It would be nice if this were supported (along with all the other functions needed for it to be useful, e.g. glfwCreateCursor and a couple related ones).

**Comment by bjz** [comment]
We are currently using 3.0.4 I think - is cursor setting released yet, or is it still just on master?

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/glfw-rs/issues/360
