### ISSUE TITLE
Can't find system glfw3 on Ubuntu 14.10

### ISSUE THREAD

**Issue by jhasse** [PistonDevelopers/glfw-rs#292]
Using `default-features = false` I'm getting `cannot find -lglfw3` when linking. The `libglfw3-dev` package installs `/usr/lib/x86_64-linux-gnu/libglfw.so`. The package conflicts with `libglfw-dev` (so you can't install both glfw 2 and 3 on ubuntu).

Is there a way to use libglfw.so as a fallback?

**Comment by bjz** [comment]
glfw brings its own copy of glfw - it doesn't rely on the global version. Is there a particular reason why you don't want it?

**Comment by jhasse** [comment]
The reason is that glfw coming with glfw-rs doesn't work on Windows and I want to be able to work on both systems.

A way to declare `default-features = false` only on Windows would also work for me ;)

**Comment by bjz** [comment]
Ah, didn't think of that! I think you might be able to do this with cargo - but I'm not sure... you might have to ask on the #cargo IRC channel.

**Comment by IcyTesseract** [comment]
The issue (I think) is that `-lglfw3` changed to `lglfw` recently on Linux. I noticed this problem (and it has an easy fix), but I'm not sure how recently this change was made and/or if it exists on most distributions.

**Comment by ProtectedMode** [comment]
@jhasse, any update on this? I am running into the same problem.

**Comment by HarryLikesCode** [comment]
@bjz, Would we want to do something like this,

1. Check if user specified a location for GLFW
  - Found: Link against it
  - Not found: Look in common locations
    - Found: Link against it
    - Not found: Build it ourselves
2. Check in common locations
  - Found: Link against it
  - Not found: build it ourselves

?
