### ISSUE TITLE
Move to Piston organisation

### ISSUE THREAD

**Issue by bjz** [PistonDevelopers/glfw-rs#330]
I'm no longer actively working on glfw-rs - I use glutin. The Piston ecosystem seems to still use glfw-rs. Would it make sense to transfer the repo there?

cc. @bvssvni

**Comment by bvssvni** [comment]
That would be good. We use it as a backup for platforms with bugs in the other window backends. I added you to the Admin group, so you should be able to transfer it.

**Comment by bjz** [comment]
Done! The `Cargo.toml`s will also have to be updated to point here.
