### ISSUE TITLE
Upgrade to glfw 3.2 with Vulkan support

### ISSUE THREAD

**Issue by humb1t** [PistonDevelopers/glfw-rs#351]
Upgrade glfw version to 3.2+ with Vulkan support http://www.glfw.org/docs/latest/vulkan_guide.html

**Comment by novacrazy** [comment]
How's this coming along? Not just Vulkan support, but being able to switch the window mode without recreating it would be very nice, plus all the other stuff from 3.2.

**Comment by novacrazy** [comment]
Currently working on this and more over at: https://github.com/novacrazy/glfw-rs

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/glfw-rs/issues/360
