### ISSUE TITLE
IBEAM_CURSOR and more cursors

### ISSUE THREAD

**Issue by codeyash** [PistonDevelopers/glfw-rs#370]
Please guide how I can use these below cursors as there are no pub fn.

```
pub const ARROW_CURSOR                 : c_int = 0x00036001; // TODO: Not yet exposed
  | pub const IBEAM_CURSOR                 : c_int = 0x00036002; // TODO: Not yet exposed
  | pub const CROSSHAIR_CURSOR             : c_int = 0x00036003; // TODO: Not yet exposed
  | pub const HAND_CURSOR                  : c_int = 0x00036004; // TODO: Not yet exposed
  | pub const HRESIZE_CURSOR               : c_int = 0x00036005; // TODO: Not yet exposed
  | pub const VRESIZE_CURSOR               : c_int = 0x00036006; // TODO: Not yet exposed
```

**Comment by novacrazy** [comment]
I could have sworn I removed those comments when I added cursor support, but oh well.

You can create a [`Cursor`](https://docs.rs/glfw/0.15.0/glfw/struct.Cursor.html) structure from a [`StandardCursor`](https://docs.rs/glfw/0.15.0/glfw/enum.StandardCursor.html) enum using [`Cursor::standard`](https://docs.rs/glfw/0.15.0/glfw/struct.Cursor.html#method.standard), then use [`set_cursor`](https://docs.rs/glfw/0.15.0/glfw/struct.Window.html#method.set_cursor) on the [`Window`](https://docs.rs/glfw/0.15.0/glfw/struct.Window.html) structure to activate it.

Later, you can use `set_cursor` again with `None` to remove any active cursors, returning to the default cursor.

**Comment by codeyash** [comment]
Yea. Sorry for reporting.

Thank you for so quick response :)

Thank you for great work on library.
