### ISSUE TITLE
Custom callbacks for window events

### ISSUE THREAD

**Issue by dj-bauer** [PistonDevelopers/glfw-rs#441]
I would like to implement custom callbacks for window events. I am searching for a function  like set_key_callback in the c implementation. I tried to figure out how c binding in rust works and to implement it on my own in the glfw-rs sourcecode. Sadly I did not go far and do not really understand further than when the first *ffi* appears in the sourcecode. I do not know if the methods are left out intentionally and I am a rust newcomer and am so not 100 percent sure if there are language specific reasons for this. I hope I did not see any obvious reasons or notes why this is not implemented.

**Comment by The-Noah** [comment]
A year later and still waiting on this 🙁

**Comment by bvssvni** [comment]
Anyone willing to make an attempt at this?
