### ISSUE TITLE
Why removing std::error::Error support?

### ISSUE THREAD

**Issue by phaazon** [PistonDevelopers/glfw-rs#456]
Hello,

In 087fc4bf7c7e441f460f0334521827be17122f7a, you removed support of `std::error::Error`, which causes a breaking-change. Would you accept a PR to re-introduce it?

![](https://phaazon.net/media/uploads/evil_grin_girl.gif)

**Comment by bvssvni** [comment]
Yeah, this was a mistake. Sorry!
