### ISSUE TITLE
what exactly is the first field of (f64, WindowEvent) from the flush_messages?

### ISSUE THREAD

**Issue by coderedart** [PistonDevelopers/glfw-rs#484]
basically that. what exactly is the first field of that tuple ? is it time? there's no documentation i could find after searching for more than an hour.

**Comment by aloucks** [comment]
[It's the timestamp of when the event callback was called](https://github.com/PistonDevelopers/glfw-rs/blob/5298cfc6464bca00c88e0e31f63cab77cf5b4bb0/src/callbacks.rs#L212).

https://www.glfw.org/docs/3.0/group__time.html#gaa6cf4e7a77158a3b8fd00328b1720a4a

**Comment by coderedart** [comment]
Ah.. thank you. idk why i didn't think of looking at the src code. I can finally close this issue :)
