### ISSUE TITLE
Window doesn't creates (on Wayland?)

### ISSUE THREAD

**Issue by dmyTRUEk** [PistonDevelopers/glfw-rs#485]
I have installed latest version of Manjaro linux, all packages are up to date, Rust 1.55.0 (stable), glfw-rs 0.42.0.
Also i have installed two DE/WM: KDE Plasma (on X11) and Sway (on Wayland).

I'm trying to run first example from README:
- On KDE everything is ok, window created and everything works fine.
- On Sway the program executes normally (no error, crashes, warnings or else in terminal), but the window doesn't appear. This is easily checked by this:
  ```
  $ swaymsg -t get_workspaces
  Workspace 1 (focused)
    Output: DP-3
    Layout: splith
    Representation: H[Alacritty]
  ```
  (alacritty is my terminal emulator, from which i run example by `cargo run`)
  So we see, that there is no window created by example program.

Also, other my projects on GLFW (using c++) are executed correctly on both DE/WM.

So that is what makes me think, that problem is in glfw-rs, and not something else.

I believe it's connected to Wayland, so i think it must be also tested on other de/wm with wayland, but i dont have such.

**Comment by dmyTRUEk** [comment]
> It works fine on Gnome with Wayland and KDE with Wayland

Hm, that was unexpected for me... So, you think problem is on Sway's side? Maybe you have ideas, what exactly may cause such problem?

**Comment by czak** [comment]
While GLFW can now [support Wayland natively](https://www.glfw.org/docs/latest/compile_guide.html#compile_options_wayland), `glfw-rs` seems to only support the X11 backend at the time being, and it builds `glfw-sys` for X11 as well.

You should still be able to run binaries fine if you install XWayland (`sway` will pick it up by default on launch).

Feel free to correct me, I'm just an observer here.
