### ISSUE TITLE
Why not `Window::set_*_callback`?

### ISSUE THREAD

**Issue by RpxdYTX** [PistonDevelopers/glfw-rs#492]
`Window::set_*_polling` ultimately enables or disables a callback to something.

This callback just updates the `WindowEvent` in the receiver you get on `glfw.create_window`, so why not a safer function to set custom callbacks and optionally to set the default callback in `set_*_polling`?

That would allow custom behaviour without needing to match against a `WindowEvent`.

**Comment by RpxdYTX** [comment]
Any info on this issue? I suggested it a long time ago.

**Comment by bvssvni** [comment]
Sounds good to me!

**Comment by RpxdYTX** [comment]
To clarify, something like:
```rust
pub fn set_*_callback(&self, callback: Option<fn (...) -> ...>, include_default: bool /* whether set_*_polling should also be include in the callback */) -> Option<fn (...) -> ...> /* previous callback, if any */
```
Of course, this could be changed to better suit the API or to make it compatible with the existing code.
