### ISSUE TITLE
vk-sys is deprecated

### ISSUE THREAD

**Issue by Hawk777** [PistonDevelopers/glfw-rs#496]
The `vk-sys` crate is deprecated. It used to be provided by the Vulkano project, but they now rely on Ash instead. While `vk-sys` still exists, it’s not receiving any updates (Vulkano no longer even has it in their repo) it might make sense to migrate to something else.

**Comment by nul-reference** [comment]
In my opinion, [ash](https://github.com/ash-rs/ash) is the best candidate. I’m willing to prepare a PR for integrating ash, but I see two ways forward:
* Remove `vk-sys` entirely and replace it with ash. This would be a breaking change but the cleanest option.
* Add a `ash` feature and leave `vk-sys` as a dependency of the `vulkan` flag. This would avoid the breaking change but be messy. 

Which is preferred?

**Comment by bvssvni** [comment]
I think migrating to Ash is fine.
