### ISSUE TITLE
Creating a maximized window

### ISSUE THREAD

**Issue by KyleNBurke** [PistonDevelopers/glfw-rs#499]
Is there any way to create a maximized window without having to do the following.

```
let (mut window, events) = glfw.create_window(1, 1, "Title", glfw::WindowMode::Windowed).unwrap();
window.maximize();
```

The documentation describes a window hit called GLFW_MAXIMIZED.
> specifies whether the windowed mode window will be maximized when created. Possible values are GLFW_TRUE and GLFW_FALSE. This hint is ignored for full screen windows.

but that hint isn't present in this crate. Is there some way to accomplish this?

**Comment by bohdloss** [comment]
You should be able to call `glfw.window_hint(WindowHint::Maximized(true));` before creating the window, but it seems the hint `WindowHint::Maximized(bool)` is missing for some reason
