### ISSUE TITLE
Allow getting glfw system library from pkg-config

### ISSUE THREAD

**Issue by Fuuzetsu** [PistonDevelopers/glfw-rs#506]
Originally a ticket from https://github.com/PistonDevelopers/glfw-sys/issues/26

I was able to verify that something like below works along with turning off the default feature of `glfw-rs` which pulls in `glfw-sys`.

Of course this needs a bit more love (made optional) but it appears to work I think.

```diff
diff --git a/Cargo.toml b/Cargo.toml
index 8a1ebf1..a87a352 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -38,7 +38,11 @@ version = "^0.4"
 [dev-dependencies]
 log = "0.4"
 
+[build-dependencies]
+pkg-config = "0.3"
+
 [features]
 all = ["image", "vulkan", "log"]
 default = ["glfw-sys"]
 vulkan = ["vk-sys"]
+
diff --git a/build.rs b/build.rs
new file mode 100644
index 0000000..6d5fe2d
--- /dev/null
+++ b/build.rs
@@ -0,0 +1,5 @@
+extern crate pkg_config;
+
+fn main() {
+    pkg_config::probe_library("glfw3").unwrap();
+}
```

**Comment by bvssvni** [comment]
The convention of using `-sys` crates is to prevent multiple linking to external libraries through Cargo. I think you can reopen the issue on the glfw-sys project.
