### ISSUE TITLE
Getting the current monitor?

### ISSUE THREAD

**Issue by shingle-bells** [PistonDevelopers/glfw-rs#517]
Hello, I'm trying to implement fullscreen and windowed modes and I can't seem to figure out how to properly get the current monitor. This is the code I was hoping would work (but unfortunately didn't, as the `ptr` field of `glfw::Monitor` is private and can't be assigned to):
```rs
let mut monitor = unsafe {
    let mut monitor = glfw::Monitor { ptr: glfw::ffi::glfwGetWindowMonitor(window.window_ptr()) };
    monitor
};
```
This is what the Window guide on the GLFW website says for C++:
```rs
GLFWmonitor* monitor = glfwGetWindowMonitor(window);
```
I'm new to Rust, so if something is obvious and I'm just missing it I apologize in advance.

**Comment by bvssvni** [comment]
Yeah, it seems that we need `Monitor::from_ptr`.

Could also add `Monitor::from_window`.
