### ISSUE TITLE
cursor position is in pixels and not screen coordinates

### ISSUE THREAD

**Issue by coderedart** [PistonDevelopers/glfw-rs#534]
idk if this issue is with glfw-rs in particular or upstream glfw, so i am starting here for now.

Both the event `CursorPos` and the fn `Window::get_cursor_pos` return the position in pixels. So, on hidpi monitors, we have to manually divide the position with scale to translate to "virtual screen coordinates".

I was just reading https://www.glfw.org/docs/3.3/intro_guide.html#coordinate_systems and it specifically mentions that almost all positions/sizes are in screen coordinates.

`GetCursorPos` also claims that it is in screen coordinates https://www.glfw.org/docs/3.3/group__input.html#ga01d37b6c40133676b9cea60ca1d7c0cc

same for the callback https://www.glfw.org/docs/3.3/input_guide.html#cursor_pos

If someone else could confirm this issue on their hidpi monitor, that would be helpful in investigating this :)

platform: latest manjaro/kde/x11 with 1.5 scale on FHD laptop 14"

**Comment by vallentin** [comment]
While the docs say "screen coordinates", there's no guarantee that these are not in pixels.

It is mentioned in the [Coordinate Systems](https://www.glfw.org/docs/3.3/intro_guide.html#coordinate_systems) section (that you linked as well), it mentions:

> GLFW has two primary coordinate systems: the virtual screen and the window content area or content area. Both use the same unit: virtual screen coordinates, or just screen coordinates, <ins>**which don't necessarily correspond to pixels**</ins>.

**Comment by coderedart** [comment]
Ah, I understand. As winit uses physical/logical coords, I accidentally assumed that screen coords meant logical. 

So, if i wanted to get the ratio of the screen vs physical coords, i should just do `framebuffer_size/window_size`.

and then multiply that ratio with cursor position to get logical position of the cursor.

**Comment by vallentin** [comment]
I can't remember a lot about HDPI currently. But also check out [Window content scale](https://www.glfw.org/docs/3.3/window_guide.html#window_scale). GLFW also defines [`glfwGetWindowContentScale`](https://www.glfw.org/docs/3.3/group__window.html#gaf5d31de9c19c4f994facea64d2b3106c), i.e. [`get_content_scale()`](https://docs.rs/glfw/0.51.0/glfw/struct.Window.html#method.get_content_scale).

Also [`WindowHint::ScaleToMonitor`](https://docs.rs/glfw/0.51.0/glfw/enum.WindowHint.html#variant.ScaleToMonitor) might be useful to you.
