### ISSUE TITLE
Crate leaks unsafe functionality into safe rust!!

### ISSUE THREAD

**Issue by GideonUng** [PistonDevelopers/glfw-rs#560]
i was writing my own wrapper and wondering how others solved wrapping monitors safely and i guess the answer is they simply dont...

there are several issues with just this screenshot where undefined behavior leaks into safe rust:
![Screenshot from 2024-01-30 01-56-39](https://github.com/PistonDevelopers/glfw-rs/assets/5054701/9902e677-f06b-4f59-aaf8-b2bbdb3c2854)

`glfwGetWindowMonitor()` might return null. this is not checked
`glfwGetMonitorPos()` it is not legal to supply null for the monitor paramter here (but might be given the function above)

and even further that monitor even saves a monitor pointer is illegal since `glfw*Events()` might invalidate those pointers making them point to trash memory. (after a monitor is disconnected)

and even further still there is no checking for the validity of the thread the monitor is created in. glfw is not thread safe for the most part and a monitor created on anything but the thread `glfwInit()` is called on is undefined behavior.

this is why i dont use any crates from crates.io. the state of rust is abysmal...

**Comment by bohdloss** [comment]
![image](https://github.com/PistonDevelopers/glfw-rs/assets/44316547/65057faa-c7f2-42ae-a9f5-185d14523719)
Whoops! Looks like that was my fault. I'm going to fix this asap. Thanks for catching that!
